# Welcome to Serverless!
#
# Happy Coding!

service: serverless-go

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  # 権限設定
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

custom:
  defaultStage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  show:
    handler: bin/show
    events:
      - http:
          path: func/{id}
          method: get
          # cognito認証を実施する場合、対象cognitoのarnを指定
          #authorizer:
          #  arn: arn:aws:cognito-idp:ap-northeast-1:982976011432:userpool/ap-northeast-1_xerpEI3kg
    environment:
      DYNAMO_DATA_TABLE:
        Ref: DynamoDataTable
  create:
    handler: bin/create
    events:
      - http:
          path: func
          method: post
    environment:
      DYNAMO_DATA_TABLE:
        Ref: DynamoDataTable
      SEQUENCE_TABLE:
        Ref: SequenceTable

# dynamoDB Create処理
resources:
  Resources:
    DynamoDataTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ID
            AttributeType: N
        KeySchema:
          -
            AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SequenceTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: TableName
            AttributeType: S
        KeySchema:
          -
            AttributeName: TableName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
